name: Visual
on: [push]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn setup
          start: yarn start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'
          # the entire command will automatically be prefixed with "npx"
          command-prefix: 'percy exec -- npx'
        env:
          # pass PERCY_TOKEN secret via environment variable
          PERCY_TOKEN: ${{ secrets.percy_token }}
